### ISSUE TITLE
setuptools ContextualVersionConflict when creating docker images

### ISSUE THREAD

**Issue by mmisono** [project-flexos/asplos22-ae#4]
When running `make prepare`, I encountered the following problem.

```
[...]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (setuptools 40.8.0 (/usr/lib/python3/dist-packages), Requirement.parse('setuptools>=41.0'), {'readchar'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/kraft", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (setuptools 40.8.0 (/usr/lib/python3/dist-packages), Requirement.parse('setuptools>=41.0'), {'readchar'})
```

The following patch fixed the problem, though I'm not sure if it is the correct way to fix it.

```diff
diff --git a/support/dockerfiles/Dockerfile.flexos-ae-base b/support/dockerfiles/Dockerfile.flexos-ae-base
index 51b50b3..548b37d 100644
--- a/support/dockerfiles/Dockerfile.flexos-ae-base
+++ b/support/dockerfiles/Dockerfile.flexos-ae-base
@@ -21,6 +21,7 @@ RUN apt install -y build-essential libncurses-dev python3 expect-dev moreutils \
        qemu-utils curl gawk git procps socat uuid-runtime python3-pip libsqlite3-dev \
        bc libiscsi-dev librbd1 libnfs-dev libgfapi0 libffi-dev libiperf-dev net-tools \
        bridge-utils iperf dnsmasq ninja-build redis-tools
+RUN pip3 install -U setuptools==41.0

 ##############
 # Tools
```

The same issue exists in https://github.com/project-flexos/unikraft/blob/staging/docker/flexos.dockerfile.

----
Environment
- Linux 5.10.145, NixOS, 22.05 (Quokka)
- Docker version 20.10.17

**Comment by hlef** [comment]
Hi @mmisono, thanks for reporting this issue!

@jkressel should have fixed this with his PR, if you still encounter the issue please let us know.
